tabWidth: 2
useTabs: false
semi: false
singleQuote: false
printWidth: 80
proseWrap: always

overrides:
  - files: "*.yaml"
    options:
      tabWidth: 2
      printWidth: 200
      bracketSpacing: false
