replicas: 1

deploymentStrategy:
  type: Recreate

image:
  tag: "11.5.1"

testFramework:
  enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - dashboard.hokaxbt.com
  tls:
    - secretName: grafana-tls
      hosts:
        - dashboard.hokaxbt.com

persistence:
  enabled: true
  size: 1Gi

sidecar:
  datasources:
    enabled: true
  dashboards:
    enabled: true
