replicas: 3
image:
  tag: "11.5.1"
testFramework:
  enabled: false
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - grafana.hokaxbt.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.hokaxbt.com
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels: {{include "grafana.selectorLabels" .}}
