image:
  tag: "2.15.0"

replicas: 1
replicationFactor: 1

volume:
  size: 50Gi
  storageClass: nvme

resources:
  requests:
    memory: "100Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "250m"
