# Docs:
# https://grafana.com/docs/mimir/latest/configure/about-configurations/
config:
  server:
    log_level: info

# Grafana Mimir docker image configuration
image:
  tag: "2.15.0"

# Replica count
replicas: 3
replicationFactor: 3

# Grafana Mimir volume
volume:
  size: 1Gi
  storageClass: null

resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "250Mi"
    cpu: "100m"
