# Docs:
# https://grafana.com/docs/mimir/latest/configure/about-configurations/
config:
  target: all

  multitenancy_enabled: false

  server:
    http_listen_port: 8080
    grpc_listen_port: 9095
    log_level: debug
    log_format: logfmt

  limits:
    compactor_blocks_retention_period: 672h # 28 days

  frontend:
    log_queries_longer_than: 10s

  blocks_storage:
    storage_prefix: "blocks"
    bucket_store:
      sync_dir: "/mimir/tsdb-sync/"
    tsdb:
      dir: "/mimir/tsdb"
      flush_blocks_on_shutdown: true
      memory_snapshot_on_shutdown: true

  compactor:
    data_dir: "/mimir/compactor"

  ruler:
    rule_path: "/mimir/ruler"

  ruler_storage:
    storage_prefix: "rulers"

  alertmanager:
    data_dir: "/mimir/alertmanager/"

  alertmanager_storage:
    storage_prefix: "alertmanager"

  memberlist:
    advertise_port: 7946
    abort_if_cluster_join_fails: true
    join_members:
      - 'dnssrv+{{ include "name" . }}-memberlist.{{ .Release.Namespace }}.svc.cluster.local:7946'

  # Common configuration to be shared between multiple components
  common:
    storage:
      backend: s3
      s3:
        bucket_name: "{{ .Values.s3.bucket }}"
        endpoint: ${S3_ENDPOINT}
        region: ${S3_REGION}
        access_key_id: ${S3_ACCESS_KEY}
        secret_access_key: ${S3_SECRET_KEY}

  # Configuration for analytics.
  usage_stats:
    enabled: false

  #
  activity_tracker:
    filepath: "/mimir/metrics-activity.log"

# Grafana Mimir docker image configuration
image:
  tag: "2.15.0"

# Replica count
replicas: 3

# Grafana Mimir S3 secret
secret: null

# Grafana Mimir volume
volume:
  size: 1Gi
  storageClass: null

s3:
  bucket: null

resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "250Mi"
    cpu: "100m"
