---
- name: Cluster | Approve all pending certificates
  hosts: control_planes
  remote_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Cluster | Approve all pending certificates
      shell: kubectl get csr -o name | xargs kubectl certificate approve
      register: approve_certificates
      changed_when: approve_certificates.rc != 0
      run_once: true
