---
- name: Cluster | Approve all pending certificates
  hosts: "{{primary_control_plane}}"
  remote_user: root
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Cluster | Approve all pending certificates
      shell: kubectl get csr -o name | xargs kubectl certificate approve
      register: approve_certificates
      changed_when: approve_certificates.rc != 0
