---
- name: Cluster | Install Helm
  hosts: control_planes
  remote_user: root
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Cluster | Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    # This is required to run kubectl or helm via ansible
    - name: Cluster | Install dependencies
      apt:
        name:
          - python3-pip
          - python3-yaml
          - python3-kubernetes
        state: present
