---
- name: Cluster | Join workers
  hosts: workers
  remote_user: root
  gather_facts: true
  tasks:
    - name: Cluster | Register token
      shell: kubeadm token create
      register: kubernetes_join_token
      delegate_to: "{{ primary_control_plane }}"
      run_once: true

    - name: Cluster | Register PKI Cert
      community.crypto.x509_certificate_info:
        path: /etc/kubernetes/pki/ca.crt
      register: kubernetes_pki_ca
      delegate_to: "{{ primary_control_plane }}"
      run_once: true

    - name: Cluster | Write worker join configuration
      template:
        src: ./files/kubeadm-join-worker.yaml
        dest: /root/join-worker.yaml

    - name: Cluster | Run kubeadm join as worker
      command: "kubeadm join --config /root/join-worker.yaml"
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Cluster | Check worker role label
      command: kubectl get node {{ inventory_hostname }} -o jsonpath='{.metadata.labels.node-role\.kubernetes\.io/worker}'
      register: worker_role
      delegate_to: "{{ primary_control_plane }}"

    - name: Cluster | Add worker role
      command: kubectl label node {{ inventory_hostname }} node-role.kubernetes.io/worker=worker
      delegate_to: "{{ primary_control_plane }}"
      when: worker_role.stdout == ""
