---
- name: Cluster | Join control planes
  hosts: control_planes
  remote_user: root
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - name: Cluster | Write configuration bootstrap.yaml
      template:
        src: ./files/bootstrap.yaml
        dest: /root/bootstrap.yaml
      when: ansible_hostname == primary_control_plane

    - name: Cluster | Run bootstrap
      command: k8s bootstrap --file /root/bootstrap.yaml
      args:
        creates: /etc/kubernetes/admin.conf
      when: ansible_hostname == primary_control_plane
