# Docs:
# https://grafana.com/docs/loki/latest/configure/

# Grafana Loki docker image configuration
image:
  tag: "3.3.2"

# Replica count
replicas: 3

# Grafana Loki volume
volume:
  size: 1Gi
  storageClass: null

resources:
  requests:
    memory: "150Mi"
    cpu: "30m"
  limits:
    memory: "250Mi"
    cpu: "100m"

server:
  httpListenPort: 3100
  grpcListenPort: 9095
  logLevel: info

memberlist:
  advertisePort: 7946
