# Docs:
# https://grafana.com/docs/loki/latest/configure/
config:
  target: all

  auth_enabled: false

  server:
    http_listen_port: 3100
    grpc_listen_port: 9095
    log_level: debug
    log_format: logfmt

  # distributor
  # querier
  # querier_rf1
  # query_scheduler

  frontend:
    log_queries_longer_than: 10s

  # query_range

  ruler:
    rule_path: "/loki/ruler"
    wal:
      dir: "/loki/ruler-wal"

  # ingester_client
  # ingester_rf1_client
  ingester:
    wal:
      enabled: true
      dir: "/loki/ingester-wal"
      flush_on_shutdown: true

  pattern_ingester:
    enabled: true

  # index_gateway

  storage_config:
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
    aws:
      bucketnames: "{{.Values.s3.bucket}}"
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET_KEY}

  chunk_store_config:
    chunk_cache_config:
      embedded_cache:
        enabled: true
        max_size_mb: 100

  schema_config:
    configs:
      - from: 2025-02-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
        chunks:
          prefix: chunks_

  compactor:
    working_directory: "/loki/compactor"
    retention_enabled: true
    delete_request_store: s3

  # compactor_grpc_client
  limits_config:
    retention_period: 672h # 28 days

  # frontend_worker
  # table_manager
  memberlist:
    advertise_port: 7946
    abort_if_cluster_join_fails: true
    join_members:
      - 'dnssrv+{{ include "name" . }}-memberlist.{{ .Release.Namespace }}.svc.cluster.local:7946'

  # runtime_config
  # operational_config
  # tracing
  analytics:
    reporting_enabled: false

  common:
    replication_factor: 3
    ring:
      kvstore:
        store: memberlist

# Grafana Mimir docker image configuration
image:
  tag: "3.3.2"

# Replica count
replicas: 3

# Grafana Mimir S3 secret
secret: null

# Grafana Mimir volume
volume:
  size: 1Gi
  storageClass: null

s3:
  bucket: null

resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "250Mi"
    cpu: "100m"
