apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "name" .}}
  labels: {{include "labels" . | nindent 4}}
data:
  config.yaml: |2

    target: all

    auth_enabled: false

    server:
      http_listen_port: {{.Values.server.httpListenPort}}
      grpc_listen_port: {{.Values.server.grpcListenPort}}
      log_level: {{.Values.server.logLevel}}
      log_format: logfmt

    # distributor
    # querier
    # querier_rf1
    # query_scheduler

    frontend:
      log_queries_longer_than: 10s

    # query_range

    ruler:
      rule_path: "/loki/ruler"
      wal:
        dir: "/loki/ruler-wal"

    # ingester_client
    # ingester_rf1_client
    ingester:
      wal:
        enabled: true
        dir: "/loki/ingester-wal"
        flush_on_shutdown: true

    pattern_ingester:
      enabled: true

    # index_gateway

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        cache_ttl: 24h # Can be increased for faster performance over longer query periods, uses more disk space
      filesystem:
        directory: /loki/chunks

    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: true
          max_size_mb: 100

    schema_config:
      configs:
        - from: 2025-02-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
          chunks:
            prefix: chunks_

    compactor:
      working_directory: "/loki/compactor"
      retention_enabled: true
      delete_request_store: filesystem

    # compactor_grpc_client
    limits_config:
      retention_period: 672h # 28 days
      volume_enabled: true

    # frontend_worker
    # table_manager
    memberlist:
      advertise_port: {{.Values.memberlist.advertisePort}}
      abort_if_cluster_join_fails: {{.Values.memberlist.abortIfClusterJoinFails}}
      join_members:
        - 'dnssrv+{{ include "name" . }}-memberlist.{{ .Release.Namespace }}.svc.cluster.local:7946'

    # runtime_config
    # operational_config
    # tracing
    analytics:
      reporting_enabled: false

    common:
      replication_factor: 3
      ring:
        kvstore:
          store: memberlist
