apiVersion: v1
kind: Service
metadata:
  name: {{include "name" .}}
  labels: {{include "labels" . | nindent 4}}
spec:
  selector: {{include "selectorLabels" . | nindent 4}}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{.Values.server.httpListenPort}}
