apiVersion: v1
kind: Service
metadata:
  name: '{{include "name" . }}-memberlist'
  labels: {{include "labels" . | nindent 4}}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{include "selectorLabels" . | nindent 4}}
  ports:
    - name: memberlist
      protocol: TCP
      port: {{.Values.memberlist.advertisePort}}
      targetPort: {{.Values.memberlist.advertisePort}}
