apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  storage: "lvm"
  vgpattern: "^ubuntu-vg$"
provisioner: local.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: disktype
        values:
          - nvme
