kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nvme-test
spec:
  storageClassName: nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nvme-test
spec:
  volumes:
    - name: nvme-test
      persistentVolumeClaim:
        claimName: nvme-test
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
        limits:
          cpu: 20m
          memory: 50Mi
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nvme-test
