engines:
  local:
    lvm:
      enabled: true
    zfs:
      enabled: false
  replicated:
    mayastor:
      enabled: false

lvm-localpv:
  analytics:
    enabled: false
  lvmPlugin:
    allowedTopologies: "kubernetes.io/hostname,disktype"

analytics:
  enabled: false
