cluster:
  name: "hoka"

global:
  scrapeInterval: 15s

destinations:
  - name: Grafana Mimir
    type: prometheus
    url: http://grafana-mimir.monitoring.svc.cluster.local/api/v1/push
  - name: Grafana Loki
    type: loki
    url: http://grafana-loki.monitoring.svc.cluster.local/loki/api/v1/push

nodeLogs:
  enabled: true

podLogs:
  enabled: true

clusterMetrics:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true
  # controller:
  #   tolerations:
  #     - key: "node-role.kubernetes.io/master"
  #       operator: "Exists"
  #       effect: "NoSchedule"
  #     - key: "node-role.kubernetes.io/control-plane"
  #       operator: "Exists"
  #       effect: "NoSchedule"

integrations:
  etcd:
    instances:
      - name: etcd-controller
        namespace: kube-system
        labelSelectors:
          app.kubernetes.io/name: etcd-controller
        logs:
          enabled: true
        metrics:
          enabled: true
