apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme
allowVolumeExpansion: true
parameters:
  storage: "lvm"
  vgpattern: "^ubuntu-vg$"
provisioner: local.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
