---
- name: Check OS Distribution
  hosts: all
  remote_user: root
  gather_facts: true
  vars:
    distribution: Ubuntu
    distribution_version: "24.04"
  tasks:
    - name: Check distribution
      assert:
        that:
          - ansible_distribution == distribution
          - ansible_distribution_version == distribution_version
        msg:
          "Expected {{distribution}} {{distribution_version}}, Got
          {{ansible_distribution}} {{ansible_distribution_version}}"
