---
- name: haproxy
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    control_planes: "{{ groups['control-planes'] }}"
  tasks:
    - name: haproxy | Show templating results
      debug:
        msg: "{{ lookup('ansible.builtin.template', './files/haproxy.cfg') }}"
