---
# Basic setup
- import_playbook: ./node/check_distro.yaml
- import_playbook: ./node/set_hostname.yaml
- import_playbook: ./node/set_dns.yaml
- import_playbook: ./node/set_ssh.yaml
- import_playbook: ./node/set_swap.yaml
- import_playbook: ./node/set_firewall_lb.yaml
- import_playbook: ./node/set_firewall_node.yaml
- import_playbook: ./node/set_modprobe.yaml
- import_playbook: ./node/set_sysctl.yaml
- import_playbook: ./node/update.yaml

# This is for the netcup servers
- import_playbook: ./node/install_qemu_guest_agent.yaml

- import_playbook: ./node/install_wireguard.yaml

# Only for the primary control plane before others joined
- import_playbook: ./node/install_haproxy.yaml
  vars:
    control_planes:
      - "{{ primary_control_plane }}"

- import_playbook: ./node/install_kubernetes.yaml
- import_playbook: ./cluster/join_control_planes.yaml

# Load balance to all control planes
- import_playbook: ./node/install_haproxy.yaml
  vars:
    control_planes: "{{ groups['control_planes'] }}"

- import_playbook: ./cluster/join_workers.yaml
# TODO: Add a playbook to install the flannel
