---
# Basic setup
- import_playbook: ./node/check_distro.yaml
- import_playbook: ./node/set_hostname.yaml
- import_playbook: ./node/set_dns.yaml
- import_playbook: ./node/set_ssh.yaml
- import_playbook: ./node/set_swap.yaml
- import_playbook: ./node/set_firewall_lb.yaml
- import_playbook: ./node/set_firewall_node.yaml
- import_playbook: ./node/set_modprobe.yaml
- import_playbook: ./node/set_sysctl.yaml
- import_playbook: ./node/update.yaml

# This is for the netcup servers
- import_playbook: ./node/install_qemu_guest_agent.yaml

# Install Wireguard
- import_playbook: ./node/install_wireguard.yaml

# Install HAProxy on load balancers
- import_playbook: ./node/install_haproxy.yaml
  vars:
    control_planes:
      - "{{ primary_control_plane }}"

# Install k8s
- import_playbook: ./node/install_kubernetes.yaml

# Initialize cluster
- import_playbook: ./cluster/init_control_planes.yaml

- import_playbook: ./node/install_haproxy.yaml
  vars:
    control_planes: "{{ groups['control_planes'] }}"

- import_playbook: ./cluster/init_workers.yaml
# TODO: Add a playbook to install the flannel
