---
- name: ETCD
  hosts: controllers
  remote_user: root
  tasks:
    - name: ETCD | Install package
      apt:
        pkg:
          - etcd-client
        state: latest
        update_cache: true

    - name: ETCD | Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: ETCD | Reboot if required
      reboot:
        reboot_timeout: 3600
      when: reboot_required_file.stat.exists == true
