---
- name: Restart kubelet
  hosts: all
  remote_user: root
  tasks:
    - name: Restart CRI-O
      service:
        name: cri-o
        state: restarted
    - name: Restart kubelet
      service:
        name: kubelet
        state: restarted
