---
- name: System | Install haproxy
  hosts: load_balancers
  remote_user: root
  vars:
    control_planes: "{{ groups['control_planes'] }}"
  tasks:
    - name: System | Install haproxy
      apt:
        name: haproxy
        state: present

    - name: System | Write configuration
      template:
        src: ./files/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
      notify: System | Restart

    - name: System | Enable haproxy
      service:
        name: haproxy
        enabled: true

  handlers:
    - name: System | Restart
      service:
        name: haproxy
        state: restarted
