---
- name: System | Set firewall for load balancer
  hosts: load_balancers
  remote_user: root
  tasks:
    - name: System | Set ufw logging
      ufw:
        logging: "on"

    - name: System | Allow SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: System | Allow HTTP
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: System | Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: System | Allow apiserver
      ufw:
        rule: allow
        port: "{{load_balancer_port}}"
        proto: tcp

    - name: System | Reject everything and enable UFW
      ufw:
        state: enabled
        policy: reject
        log: yes
