---
- name: System | Set sysctl
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: System | Set net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: System | Set net.bridge.bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: System | Set net.bridge.bridge-nf-call-ip6tables
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: "1"
        sysctl_set: true
        state: present
        reload: true
