apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources-mimir
  namespace: monitoring
  labels:
    grafana_datasource: "1"
stringData:
  data.yaml: |-
    apiVersion: 1
    datasources:
      - name: Grafana Mimir
        type: prometheus
        uid: grafana-mimir
        url: http://grafana-mimir.monitoring.svc.cluster.local/prometheus
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "15s"
          prometheusType: Mimir
          cacheLevel: High
