apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources-tempo
  namespace: monitoring
  labels:
    grafana_datasource: ""
stringData:
  data.yaml: |-
    apiVersion: 1
    datasources:
      - name: Grafana Tempo
        type: tempo
        uid: grafana-tempo
        url: http://grafana-tempo.monitoring.svc.cluster.local
        isDefault: false
        editable: false
