apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "{{wireguard_ip}}"
  bindPort: 6443
certificateKey: "{{kubernetes_join_certificate_key.stdout}}"
bootstrapTokens:
  - token: "{{kubernetes_join_token.stdout}}"
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: "{{kubernetes_pod_cidr}}"
  dnsDomain: cluster.local
controlPlaneEndpoint: "{{load_balancer_dns}}:{{load_balancer_port}}"
apiServer:
  certSANs:
    - "{{load_balancer_dns}}"
clusterName: "hokaxbt"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: iptables
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
imageMinimumGCAge: 2m
imageMaximumGCAge: 24h
imageGCHighThresholdPercent: 60
imageGCLowThresholdPercent: 50
