apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "name" .}}
  labels: {{include "labels" . | nindent 4}}
data:
  config.yaml: |2

    target: all

    multitenancy_enabled: false

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
      log_level: {{.Values.config.server.log_level}}
      log_format: logfmt

    ingester:
      ring:
        replication_factor: {{.Values.replicationFactor}}

    limits:
      compactor_blocks_retention_period: 672h # 28 days

    frontend:
      log_queries_longer_than: 10s

    blocks_storage:
      storage_prefix: "blocks"
      bucket_store:
        sync_dir: "/mimir/tsdb-sync/"
      tsdb:
        dir: "/mimir/tsdb"
        flush_blocks_on_shutdown: true
        memory_snapshot_on_shutdown: true

    compactor:
      data_dir: "/mimir/compactor"

    store_gateway:
      sharding_ring:
        replication_factor: {{.Values.replicationFactor}}

    ruler:
      rule_path: "/mimir/ruler"

    ruler_storage:
      storage_prefix: "rulers"

    alertmanager:
      data_dir: "/mimir/alertmanager/"
      sharding_ring:
        replication_factor: {{.Values.replicationFactor}}

    alertmanager_storage:
      storage_prefix: "alertmanager"

    memberlist:
      advertise_port: 7946
      abort_if_cluster_join_fails: true
      # join_members:
      #   - 'dnssrv+{{ include "name" . }}-memberlist.{{ .Release.Namespace }}.svc.cluster.local:7946'

    # Common configuration to be shared between multiple components
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: "/mimir/data"

    # Configuration for analytics.
    usage_stats:
      enabled: false

    #
    activity_tracker:
      filepath: "/mimir/metrics-activity.log"
