# Docs:
# https://grafana.com/docs/tempo/latest/configuration/
server:
  httpListenPort: 3200
  grpcListenPort: 9095
  logLevel: info

memberlist:
  advertisePort: 7946
  abortIfClusterJoinFails: true

# Grafana Tempo docker image configuration
image:
  tag: "2.7.0"

# Replica count
replicas: 3

# Grafana Tempo S3 secret
secret: null

# Grafana Tempo volume
volume:
  size: 1Gi
  storageClass: null

s3:
  bucket: null

resources:
  requests:
    memory: "100Mi"
    cpu: "10m"
  limits:
    memory: "250Mi"
    cpu: "100m"
