---
- name: System | Check Distro
  hosts: all
  remote_user: root
  gather_facts: true
  tasks:
    - name: System | Check distro
      assert:
        that:
          - ansible_distribution == distro_name
          - ansible_distribution_version == distro_version
        msg: "Expected {{distro_name}} {{distro_version}}, Got {{ansible_distribution}} {{ansible_distribution_version}}"
