---
- name: Node | Install etcdctl
  hosts: control_planes
  remote_user: root
  gather_facts: false
  tasks:
    - name: Node | Install package
      apt:
        pkg:
          - etcd-client
        state: latest
        update_cache: true

    - name: Node | Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Node | Reboot if required
      reboot:
        reboot_timeout: 3600
      when: reboot_required_file.stat.exists == true
