---
- name: System | Install snapd
  hosts: control_planes,workers
  remote_user: root
  gather_facts: false
  tasks:
    - name: System | Install snapd
      apt:
        name: snapd
        state: present
