---
- name: Node | Set firewall for load balancer
  hosts: load_balancers
  remote_user: root
  tasks:
    - name: Node | Set ufw logging
      ufw:
        logging: "on"

    - name: Node | Allow SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Node | Allow HTTP
      ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Node | Allow HTTPS
      ufw:
        rule: allow
        port: "443"
        proto: tcp

    - name: Node | Allow apiserver
      ufw:
        rule: allow
        port: "{{load_balancer_port}}"
        proto: tcp

    - name: Node | Reject everything and enable UFW
      ufw:
        state: enabled
        policy: reject
        log: yes
