---
- name: Node | Turn Off Swap
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Node | swapoff
      shell: |
        swapoff -a
    - name: Node | Enable swapoff across reboot
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
