---
- name: Node | Setup SSH
  hosts: all
  remote_user: root
  gather_facts: false
  tasks:
    - name: Node | Add authorized keys on host
      authorized_key:
        user: root
        state: present
        key: https://github.com/hokaxbt.keys

    - name: Node | Disable empty password login
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^#?PermitEmptyPasswords"
        line: "PermitEmptyPasswords no"
      notify: Node | Restart sshd

    - name: Node | Disable password login
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: '^(#\s*)?PasswordAuthentication '
        line: "PasswordAuthentication no"
      notify: Node | Restart sshd

  handlers:
    - name: Node | Restart sshd
      service:
        name: ssh
        state: restarted
