---
- name: Node | Set firewall for nodes
  hosts: control_planes,workers
  remote_user: root
  tasks:
    - name: Node | Set ufw logging
      ufw:
        logging: "on"

    - name: Node | Allow SSH
      ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Node | Reject everything and enable UFW
      ufw:
        state: enabled
        policy: reject
        log: yes
