---
- name: Uninstall Calico
  hosts: all
  remote_user: root
  tasks:
    - name: Uninstall Calico | Remove 10-calico.conflist
      file:
        path: /etc/cni/net.d/10-calico.conflist
        state: absent

    - name: Uninstall Calico | Remove 10-crio-bridge.conflist.disabled
      file:
        path: /etc/cni/net.d/10-crio-bridge.conflist.disabled
        state: absent

    - name: Uninstall Calico | Remove calico-kubeconfig
      file:
        path: /etc/cni/net.d/calico-kubeconfig
        state: absent

    - name: Uninstall Calico | Cleaning all calico
      shell: |
        for i in `iptables -L | grep cali | awk '{print $2}'`; do iptables -F $i && iptables -X $i; done

    - name: Uninstall Calico | Remove all calico links in all nodes
      shell: |
        ip link list | grep cali | awk '{print $2}' | cut -c 1-15 | xargs -I {} ip link delete {}

    - name: Uninstall Calico | Restart kubelet
      service:
        name: kubelet
        state: restarted
